Section Gérer mes alertes
ericforgues/mutuali pull request #5
Opened 2023-02-27 14:04 UTC by ericforgues

Liste des alertes + action pour delete,modifier

2023-02-27 15:53 UTC, AnneMoncionSig requested changes

2023-02-27 15:53 UTC, AnneMoncionSig commented on YellowDuck.FE/src/components/alert/snippet.vue
> +      if (this.alert.dayAvaiability) content.push(this.$t("label.ad-dayAvailability"));
Petite typo : "dayAvailability"

2023-02-27 15:53 UTC, AnneMoncionSig commented on YellowDuck.FE/src/components/alert/snippet.vue
> +      if (this.alert.eveningAvaiability) content.push(this.$t("label.ad-eveningAvailability"));
Idem, eveningAvailability

2023-02-27 15:53 UTC, AnneMoncionSig commented on YellowDuck.FE/src/components/pages/alert/list.vue
> +    position: absolute;
Je crois que la section __bottom devrait avoir une position sticky plutôt que absolute, parce que si le contenant d'alerte devient plus haut que la surface visible de l'écran, on ne verra pas le bouton avant de scroller tout en bas de la page. Peut-être se fier à comment le bouton de "Modification d'une annonce" a été implémenté ?

2023-02-27 15:53 UTC, AnneMoncionSig commented on YellowDuck.FE/src/components/alert/snippet.vue
> +  &__alert-link {
Ça se peut que je me trompe, mais je ne vois pas d'endroit où c'est utilisé ?

2023-02-27 16:27 UTC, joc-sigmund approved these changes

2023-03-02 21:07 UTC, ericforgues commented on YellowDuck.FE/src/components/pages/alert/list.vue
> +    position: absolute;
J'ai essayé, mais j'ai de la misère à le placer. Je vais ajouter ceci à ta carte d'ajustement.

2023-03-07 22:31 UTC, merged